endpoint:
  url: http://localhost:8080
  prompt: "explain why the sky is blue"
  model: "mistralai/Mistral-7B-Instruct-v0.3"
metrics:
  url: http://localhost:8080/metrics
  interval: 10
  output: ./output/