name: Build and Push Golang App to GHCR

on:
  workflow_dispatch:
      
jobs:
  
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
      
      - name: Install dependencies
        working-directory: ./vllm-simple-performance
        run: go mod download

      - name: Build
        working-directory: ./vllm-simple-performance
        run: go build -o performance ./cmd/performance

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: ./vllm-simple-performance/performance
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}